#############################################################################
# Makefile for building: CSV_Editor
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Sep 24 22:37:19 2017
# Project:  CSV_Editor.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile CSV_Editor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = csvMwindow.cpp \
		MainWindow.cpp \
		Application.cpp \
		FileData.cpp moc_csvMwindow.cpp \
		moc_MainWindow.cpp \
		qrc_CE_RSRC.cpp
OBJECTS       = csvMwindow.o \
		MainWindow.o \
		Application.o \
		FileData.o \
		moc_csvMwindow.o \
		moc_MainWindow.o \
		qrc_CE_RSRC.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CSV_Editor.pro
QMAKE_TARGET  = CSV_Editor
DESTDIR       = 
TARGET        = CSV_Editor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_csvMwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CSV_Editor.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile CSV_Editor.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile CSV_Editor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CSV_Editor1.0.0 || $(MKDIR) .tmp/CSV_Editor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CSV_Editor1.0.0/ && $(COPY_FILE) --parents csvMwindow.h ui_csvMwindow.h MainWindow.h FileData.h .tmp/CSV_Editor1.0.0/ && $(COPY_FILE) --parents CE_RSRC.qrc .tmp/CSV_Editor1.0.0/ && $(COPY_FILE) --parents csvMwindow.cpp MainWindow.cpp Application.cpp FileData.cpp .tmp/CSV_Editor1.0.0/ && $(COPY_FILE) --parents csvMwindow.ui .tmp/CSV_Editor1.0.0/ && (cd `dirname .tmp/CSV_Editor1.0.0` && $(TAR) CSV_Editor1.0.0.tar CSV_Editor1.0.0 && $(COMPRESS) CSV_Editor1.0.0.tar) && $(MOVE) `dirname .tmp/CSV_Editor1.0.0`/CSV_Editor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CSV_Editor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_csvMwindow.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_csvMwindow.cpp moc_MainWindow.cpp
moc_csvMwindow.cpp: csvMwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) csvMwindow.h -o moc_csvMwindow.cpp

moc_MainWindow.cpp: ui_csvMwindow.h \
		FileData.h \
		MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

compiler_rcc_make_all: qrc_CE_RSRC.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_CE_RSRC.cpp
qrc_CE_RSRC.cpp: CE_RSRC.qrc \
		Icons/settings.svg \
		Icons/Filter.svg \
		Icons/Find.svg \
		Icons/SortAsc.svg \
		Icons/RW.svg \
		Icons/New.svg \
		Icons/SortDesc.svg \
		Icons/Error.svg \
		Icons/Save.svg \
		Icons/ROnly.svg \
		Icons/Analysis.svg \
		Icons/Bookmark.svg \
		Icons/Open.svg \
		Icons/SaveAS
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name CE_RSRC CE_RSRC.qrc -o qrc_CE_RSRC.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_csvMwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_csvMwindow.h
ui_csvMwindow.h: csvMwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic csvMwindow.ui -o ui_csvMwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

csvMwindow.o: csvMwindow.cpp csvMwindow.h \
		ui_csvMwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o csvMwindow.o csvMwindow.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_csvMwindow.h \
		FileData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

Application.o: Application.cpp csvMwindow.h \
		ui_csvMwindow.h \
		MainWindow.h \
		FileData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Application.o Application.cpp

FileData.o: FileData.cpp FileData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileData.o FileData.cpp

moc_csvMwindow.o: moc_csvMwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_csvMwindow.o moc_csvMwindow.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

qrc_CE_RSRC.o: qrc_CE_RSRC.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_CE_RSRC.o qrc_CE_RSRC.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

